huh:
  list:
    items:
      - { name: ml_product_default, class: HeimrichHannot\MediaLibraryBundle\Item\DefaultProductListItem }
      - { name: ml_download_default, class: HeimrichHannot\MediaLibraryBundle\Item\DefaultDownloadListItem }
