huh:
    encore:
        entries:
            - { name: contao-media-library-bundle, file: "vendor/heimrichhannot/contao-media-library-bundle/src/Resources/public/js/jquery.media-library-bundle.es6.js" }