huh_encore:
    js_entries:
       - { name: contao-media-library-bundle, file: "vendor/heimrichhannot/contao-media-library-bundle/src/Resources/assets/js/contao-media-library-bundle.js", requires_css: true }
