services:
  _defaults:
    public: true
    autowire: true
    bind:
      $bundleConfig: "%huh_media_library%"

  HeimrichHannot\MediaLibraryBundle\DataContainer\:
    resource: '../../DataContainer/*'
