services:
  HeimrichHannot\MediaLibraryBundle\:
    resource: '../../{Asset,Migration,EventListener,FormType}/*'
    autowire: true
    autoconfigure: true

  huh.media_library.ajax_manager:
    public: true
    class: HeimrichHannot\MediaLibraryBundle\Manager\AjaxManager
    arguments:
      - "@contao.framework"
      - "@translator"
      - "@huh.utils.file"
      - "@huh.ajax"
