services:
  HeimrichHannot\MediaLibraryBundle\:
    resource: '../../{Asset,Controller,EventListener,FormType,Migration,Product,Security}/*'
    exclude: '../../Product/Product.php'
    autowire: true
    autoconfigure: true

  huh.media_library.ajax_manager:
    public: true
    class: HeimrichHannot\MediaLibraryBundle\Manager\AjaxManager
    arguments:
      - "@contao.framework"
      - "@translator"
      - "@huh.utils.file"
      - "@huh.ajax"
