services:
  huh.media_library.ajax_manager:
    public: true
    class: HeimrichHannot\MediaLibraryBundle\Manager\AjaxManager
    arguments:
      - "@contao.framework"
      - "@translator"
      - "@huh.utils.file"
      - "@huh.ajax"
  huh.media_library.tag_manager.product:
    class: Codefog\TagsBundle\Manager\DefaultManager
    arguments:
      - "@contao.framework"
      - "tl_ml_product"
      - "tags"
    tags:
      - { name: codefog_tags.manager, alias: huh.media_library.tags.product }
