services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $bundleConfig: '%huh_media_library%'

    Psr\Log\LoggerInterface:
        alias: monolog.logger.contao

    HeimrichHannot\MediaLibraryBundle\:
        resource: ../src
        exclude:
            - ../src/{Contao,ContaoManager,DependencyInjection,Model}
            - ../src/Product/Product.php

    HeimrichHannot\MediaLibraryBundle\Migration\RenameProductTablesMigration:
        tags:
            - { name: contao.migration, priority: 200 }

    HeimrichHannot\MediaLibraryBundle\Migration\RenameColumnsMigration:
        tags:
            - { name: contao.migration, priority: 50 }

    HeimrichHannot\MediaLibraryBundle\DataContainer\:
        resource: '../src/DataContainer'
        public: true
